services:
  mongodb:
    image: mongo:latest
    container_name: local-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: drkrieger
      MONGO_INITDB_ROOT_PASSWORD: guest
    volumes:
      - ./dbData:/data/db

volumes:
  dbData:
    driver: local
